### ISSUE TITLE
Gemfile

### ISSUE THREAD

**Issue by frgooall** [vigetlabs/active_admin_associations#1]
FYI... This may be my system, but when I added it to the gemfile <code>gem 'aa_associations'</code> it render the following error;

<code>Could not find gem 'aa_associations (>= 0) ruby' in the gems available on this machine.</code>

All went well when I used the git url.  Thanks for the providing this gem, will be helpful because my current project involves lots of associations.

Best,
Fritz

**Comment by megatux** [comment]
Yeah, when will be available on rubygems.org ?

Thanks!
  Cristian

**Comment by brianjlandau** [comment]
Just released https://rubygems.org/gems/aa_associations. I'll be doing a blog post on this gem soon here: http://viget.com/extend

Thanks for the interest!
