### ISSUE TITLE
(Support Question) Routes are not being setup correctly

### ISSUE THREAD

**Issue by joelcollinsdc** [vigetlabs/active_admin_associations#21]
Relative rails newb here, Can someone please let me know what I'm doing wrong?

I put 

```
config.activeadmin_associations.autocomplete_models = %w(provider airport)
```

in my application.rb file.  I can validate through the rails console that this is being set correctly.  However, the /autocomplete route still doesn't show up in my routes.  I had to manually add in the autocomplete route for the gem to work.  

```
  get '/autocomplete/provider' => 'autocomplete#index', :model => "provider",
      :defaults => { :format => 'json' }
  get '/autocomplete/airport' => 'autocomplete#index', :model => "airport",
      :defaults => { :format => 'json' }
```

Using the 1.0 master branch...

**Comment by brianjlandau** [comment]
You should have this in your `Gemfile`:

``` ruby
gem "rails", "~> 4.2.1"

# ...

gem 'activeadmin', '1.0.0.pre1'
gem 'activeadmin_associations', github: 'vigetlabs/active_admin_associations', branch: 'activeadmin-1.0'
```

Make sure this line is in your `config/routes.rb` file:

``` ruby
mount ActiveAdminAssociations::Engine, at: '/'
```

Then if you run `bundle exec rake routes` you should see this at the bottom (or near the bottom):

```
Routes for ActiveAdminAssociations::Engine:
       GET  /autocomplete/:model(.:format) autocomplete#index {:model=>/(provider|airport)/, :format=>"json"}
```

I think the `mount` line is missing from the `README`. I'll add that.

**Comment by brianjlandau** [comment]
Never mind it is there in the `activeadmin-1.0` branch: https://github.com/vigetlabs/active_admin_associations/tree/activeadmin-1.0#setting-up-autocomplete

**Comment by joelcollinsdc** [comment]
Thanks, must have been looking at readme on master instead of on the other branch.
