### ISSUE TITLE
Overriding templates

### ISSUE THREAD

**Issue by mscifo** [vigetlabs/active_admin_associations#3]
How can I override the default templates without editing them inside the gem?

I've created `app/views/admin/RESOURCE_NAME/_form.html.erb` and `app/views/admin/RESOURCE_NAME/_collection_table.html.erb`.

I can see that it's using my `_form.html.erb`, but any changes I've made to my `_collection_table.html.erb` are not taking affect.

**Comment by brianjlandau** [comment]
You can override the whole form template on a per resource level like you mention above if you put `form :partial => 'form'` in your AA resource 

You can override `_collection_table.html.erb` for the whole app by creating a file at `app/views/admin/shared/_collection_tabe.html.erb` inside your own app, however you can't do this at the individual resource level.

**Comment by brianjlandau** [comment]
Closing, please respond if you still have questions.
